name: mapako02
description: A new Flutter project.


publish_to: 'none'


version: 1.0.0+1


environment:  #">=2.16.2 <3.0.0"
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^1.3.0
  cloud_firestore: ^2.3.0
  provider: ^5.0.0
  firebase_auth: ^2.0.0
  qr_flutter: ^4.0.0
  firebase_storage: ^10.0.1
  flutter_svg: ^0.22.0
  url_launcher: ^6.0.9
  connectivity: ^3.0.6
  dotted_line: ^3.0.0
  permission_handler: ^8.1.6
  image_picker: ^0.8.5+3
  qr_code_scanner: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.1


flutter_icons:
  android: true
  ios: true
  image_path: "images/app_icon.png"


flutter:
  uses-material-design: true
  assets:
    - images/
    - images/bottom_nav/
    - images/header_icons/
    - images/footer_icons/
    - images/tutorials/
  fonts:
    - family: MPlusR
      fonts:
        - asset: fonts/MPLUSRounded1c-Regular.ttf
    - family: MPlus
      fonts:
        - asset: fonts/MPLUSRounded1c-Bold.ttf